version: "3.2"
services:
  mariadb:
    restart: always
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - railroad
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    restart: always
    depends_on:
      - rails
      - tileserver
    environment:
      - NGINX_PORT=${NGINX_PORT:-3000}
      - NODE_ENV=development
      - RAILS_ENV=development
    image: 'nginx:latest'
    networks:
      - tilenet
      - railroad
    ports:
      - ${NGINX_PORT:-3000}:80
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/static:/www/static
      - ./rails/app/assets:/www/static/assets

  rails:
    restart: always
    build:
      context: ./rails
    image: terrastories/rails
    labels:
      kompose.service.type: nodeport
    environment:
      - DATABASE_URL=mysql2://mariadb/terrastories_development
    depends_on:
      - tileserver
      - mariadb
    networks:
      - railroad
    tty: true # Enables debugging capabilities when attached to this container.
    volumes:
      - ./media:/media:rw
      - ./rails:/app
      - ./rails/nginx:/etc/nginx:rw

  tilebuilder:
    build:
      context: ./tilebuilder
    image: terrastories/tilebuilder
    network_mode: none
    volumes:
      - type: bind
        source: ./tilebuilder/script
        target: /script
      - type: bind
        source: mbtiles
        target: /data/mbtiles
      - type: bind
        source: ./tilebuilder/shapefiles
        target: /data/shapefiles

  tileserver:
    restart: always
    image: klokantech/tileserver-gl
    networks:
      - tilenet
    volumes:
      - type: bind
        source: ./tileserver/data
        target: /data
      - type: bind
        source: mbtiles
        target: /data/mbtiles

networks:
  railroad:
  tilenet:

volumes:
  mbtiles:
  dbdata:
