version: "3.2"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - railroad
    volumes:
      - ./data:/bitnami/mariadb/data

  nginx:
    depends_on:
      - rails
      - tileserver
    environment:
      - NGINX_PORT=${NGINX_PORT:-3000}
    image: 'nginx:latest'
    networks:
      - tilenet
      - railroad
    ports:
      - ${NGINX_PORT:-3000}:80
    volumes:
      - ./nginx:/etc/nginx

  rails:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/rails:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DATABASE_URL=mysql2://mariadb/terrastories_development
    depends_on:
      - tileserver
      - mariadb
    networks:
      - railroad
    volumes:
      - ./media:/media:rw
      - ./rails:/app
      - ./rails/nginx:/etc/nginx

  tilebuilder:
    build:
      context: ./tilebuilder
    image: terrastories/tilebuilder
    network_mode: none
    volumes:
      - type: bind
        source: ./tilebuilder/script
        target: /script
      - type: bind
        source: mbtiles
        target: /data/mbtiles
      - type: bind
        source: ./tilebuilder/shapefiles
        target: /data/shapefiles

  tileserver:
    image: klokantech/tileserver-gl
    networks:
      - tilenet
    volumes:
      - type: bind
        source: ./tileserver/data
        target: /data
      - type: bind
        source: mbtiles
        target: /data/mbtiles

networks:
  railroad:
  tilenet:

volumes:
  mbtiles:
