version: "3.0"
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}

  webpacker:
    image: ${DOCKER_IMAGE_NAME-dockerrailsdemo}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/opt/dockerrailsdemo:cached
    ports:
      - 3035:3035

  web:
    image: ${DOCKER_IMAGE_NAME-dockerrailsdemo}
    build:
      context: .
      args:
        precompileassets: "not"
    links:
      - db
      - webpacker
    ports:
      - 3000:3000
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/opt/dockerrailsdemo:cached