version: "3.7"

x-web-common: &x-web-common
  image: ${DOCKER_IMAGE_NAME:-terrastories}
  build:
    context: ./rails
    args:
      precompileassets: "not"
  env_file:
    - .env

services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  # webpacker:
  #   image: ${DOCKER_IMAGE_NAME-terrastories}
  #   command: ["./scripts/start_webpack_dev.sh"]
  #   volumes:
  #     - ./rails:/opt/terrastories:cached
  #   ports:
  #     - 3035:3035

  web:
    <<: *x-web-common
    command: scripts/server
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./rails:/opt/terrastories:cached
      - ./data/media:/media
      - ./data/import/media:/opt/terrastories/import/media

  web-test:
    <<: *x-web-common
    environment:
      RAILS_ENV: test
    command: scripts/test-server
    ports:
      - 3001:3000
    depends_on:
      - db
    volumes:
      - ./rails:/opt/terrastories:cached

  selenium:
    # Debug version enables VNC ability
    image: selenium/standalone-chrome-debug:3.0.1-germanium
    # Bind selenium port & VNC port
    ports: ['4444:4444', '5900:5900']
    logging:
      # Disable noisy logs.
      driver: none
    # bump this number up if pages are crashing
    shm_size: '256mb'

  e2e:
    build:
      context: ./e2e
    volumes:
      - ./e2e:/opt/terrastories_e2e:cached
    environment:
      TEST_APP_HOST: web-test
      TEST_APP_PORT: 3000
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    depends_on:
      - web-test
      - selenium

volumes:
  postgres_data:
  mbtiles:
